version: '3'
services:
  node:
    restart: always
    build: backend
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/code
  mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: