version: '3'
services:
  node:
    command: npm run test:watch
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./server/:/usr/src/app/server
  mongo:
    restart: always
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: